version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: fuel_postgis_db
    environment:
      POSTGRES_DB: fuel_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: fuel_django_api
    command: >
      sh -c "python manage.py migrate &&
             python manage.py import_fuel_prices &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=django-insecure-fuel-route-optimizer-assessment-key-change-in-prod
      - DEBUG=True
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=fuel_db
      - DB_USER=postgres
      - DB_PASSWORD=postgrespassword
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

volumes:
  postgres_data:
