# Generated by Django 6.1.1 on 2026-09-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=255, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('display_name', models.CharField(blank=True, max_length=500)),
                ('state', models.CharField(blank=True, max_length=10)),
                ('country_code', models.CharField(default='us', max_length=10)),
                ('raw_response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouteCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('distance_miles', models.FloatField()),
                ('duration_seconds', models.FloatField()),
                ('geometry', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.BigIntegerField(help_text='OPIS Truckstop ID from workbook')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(db_index=True, max_length=10)),
                ('rack_id', models.BigIntegerField()),
                ('retail_price', models.DecimalField(db_index=True, decimal_places=4, max_digits=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geocode_status', models.CharField(choices=[('SUCCESS', 'Successfully Geocoded'), ('FAILED', 'Geocoding Failed'), ('AMBIGUOUS', 'Ambiguous Address'), ('EXCLUDED_NON_US', 'Excluded Non-US Region')], db_index=True, default='SUCCESS', max_length=50)),
                ('geocode_provider', models.CharField(default='geocoded_fixture_v1', max_length=50)),
                ('geocode_confidence', models.FloatField(default=1.0)),
                ('dataset_version', models.CharField(default='v1.0', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fuel Station',
                'verbose_name_plural': 'Fuel Stations',
                'indexes': [models.Index(fields=['state', 'retail_price'], name='fuel_routes_state_ed0f75_idx'), models.Index(fields=['latitude', 'longitude'], name='fuel_routes_latitud_f5abd9_idx'), models.Index(fields=['source_id'], name='fuel_routes_source__7c41cc_idx'), models.Index(fields=['geocode_status'], name='fuel_routes_geocode_a017a3_idx')],
            },
        ),
    ]
